# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  nodejs_version: "6"

build: off

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
  - npm config set loglevel warn

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run lint
  - npm run build
  - npm run test:once